{{- if .Values.managedServiceAccount }}
apiVersion: {{ .Values.apiVersions.serviceAccount }}
kind: ServiceAccount
metadata:
  name: docker-collector-metrics
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: docker-collector-metrics
{{- end -}}